name: Blender daily build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches:
      - main
      - 'run-ci/**'
  pull_request:

jobs:
  build_blender:
    name: Build Blender
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Blender source code from Blender official repository
        run: |
          mkdir -p blender-build
          cd blender-build
          git clone https://projects.blender.org/blender/blender.git
      - name: Install initial packages
        run: |
          sudo apt update
          sudo apt install python3 git git-lfs
      - name: Install basic building environment
        run: |
          cd blender-build/blender
          ./build_files/build_environment/install_linux_packages.py
      - name: Download libraries
        run: |
          cd blender-build/blender
          ./build_files/utils/make_update.py --use-linux-libraries
      - name: Build Blender
        run: |
          cd blender-build/blender
          make update
          make
      - name: Test Blender Binary
        run: |
          ./blender-build/build_linux/bin/blender --background --factory-startup -noaudio
      - name: Compress Blender for the artifacts
        run: |
          mkdir release
          cp -r blender-build/build_linux/bin release/blender
          cd release
          tar Jcf blender.tar.xz blender
          rm -rf blender
      - name: Create MD5 checksum file
        run: |
          cd release
          md5sum blender.tar.xz > blender.tar.xz.md5
      - name: Upload artifact 
        uses: actions/upload-artifact@v4
        with:
          name: blender
          path: "release"
